"""
Terraform plan JSON scanner.

Reads the JSON produced by ``terraform show -json plan.out`` and runs all
registered security checks against every resource's ``change.after`` block.

Usage::

    from cloudsentry_cli.scanner import scan_plan

    findings = scan_plan("tfplan.json")
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from cloudsentry_cli.checks import CHECKS


def scan_plan(input_path: str) -> list[dict[str, Any]]:
    """Parse *input_path* (Terraform plan JSON) and return all findings.

    Parameters
    ----------
    input_path:
        Path to a Terraform plan JSON file generated by
        ``terraform show -json plan.out``.

    Returns
    -------
    list[dict]
        Every finding produced by all registered checks.  An empty list means
        no issues were detected.
    """
    plan = _load_plan(input_path)
    findings: list[dict[str, Any]] = []

    for change_entry in plan.get("resource_changes", []):
        resource_type: str = change_entry.get("type", "")
        resource_name: str = change_entry.get("name", "")
        change: dict[str, Any] = change_entry.get("change", {})
        actions: list[str] = change.get("actions", [])

        # Only evaluate resources being created or updated (not deleted/no-ops)
        if not _is_active_change(actions):
            continue

        after: dict[str, Any] = change.get("after") or {}

        for check_fn in CHECKS:
            findings.extend(check_fn(resource_type, resource_name, after))

    return findings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_plan(path: str) -> dict[str, Any]:
    """Load and return the parsed Terraform plan JSON."""
    plan_path = Path(path)
    if not plan_path.exists():
        raise FileNotFoundError(f"Terraform plan file not found: {path}")
    with plan_path.open() as fh:
        return json.load(fh)


def _is_active_change(actions: list[str]) -> bool:
    """Return True for resources being created, updated, or replaced."""
    active = {"create", "update"}
    return bool(active.intersection(actions))
